export const notifs = [
    "WELCOME TO SCAMCENTER!\n\nTHANK YOU FOR YOUR MEMBERSHIP IN SCAMCENTER. YOUR INTRODUCTORY MEMBERSHIP FEE OF $1200 HAS BEEN DEDUCTED FROM YOUR ACCOUNT.\n\nYOUR MEMBERSHIP WILL RENEW IN 10 DAYS.\n\nHAPPY SCAMMING!\n\n-- Jeremy CEO",
    "THANK YOU FOR RENEWING YOUR MEMBERSHIP IN SCAMCENTER.\n\nNOW CHOOSE YOUR FREE GIFT!\n\n--Jeremy CEO",
    "THANK YOU FOR RENEWING YOUR MEMBERSHIP IN SCAMCENTER.\n\nNOW CHOOSE YOUR FREE GIFT!\n\n--Jeremy CEO",
    "THANK YOU FOR RENEWING YOUR MEMBERSHIP IN SCAMCENTER.\n\nNOW CHOOSE YOUR FREE GIFT!\n\n--Jeremy CEO",
    "THANK YOU FOR RENEWING YOUR MEMBERSHIP IN SCAMCENTER.\n\nNOW CHOOSE YOUR FREE GIFT!\n\n--Jeremy CEO"
]