export const notifs = [
    "WELCOME TO SCAMCENTER!\n\nTHANK YOU FOR YOUR MEMBERSHIP IN SCAMCENTER. YOUR INTRODUCTORY MEMBERSHIP FEE OF $1000 HAS BEEN DEDUCTED FROM YOUR ACCOUNT.\n\nYOUR MEMBERSHIP WILL RENEW IN 10 DAYS.\n\nHAPPY SCAMMING!\n\n-- Jeremy CEO"
]